%% Doc
% This function translates bead coordinates in the reference frame of the
%   CFD computation, reading from Position_<uni_name>_BeforeRot.dat.
% The coordinates in the file should be generated by python script whose  
%   version is later than 2017-June. They were essenstially manually
%   measured via ImageJ. Raw measurement sequence is: cell center, distal
%   end of the cell body (near the point where flagella meet), bead center.
% 
% beadcoords_pth: The filepath of Position_<uni_name>_BeforeRot.dat
% pt            : Name of the case folder. Usually it is an element of 
%                 pt_list that is looped through. 
%                 NOTE: can also be a list of numbers, then xgb,ygb will be
%                       a list of the same size
% experiment    : String of experiment name, e.g. '170502c5g2', '170703c9l'
%                 Or it can simply be a 6-digit string of date such as 
%                 '170502'
% NOTE: STRING FORMAT OF DATE IS ALWAYS YYMMDD or YYYYMMDD

function [xgb,ygb] = BeadCoordsFromFile(beadcoords_pth,pt,experiment)
    if nargin<3
        error('Input incomplete')
    end
    
    %% Determine experiment date (EXP_date)
    switch length(experiment)
        case 6
            EXP_date = str2double(experiment);
        case 8
            warning(['experiment date is an 8-digit string,',...
                     'read with format YYYYMMDD']);
            EXP_date = str2double(experiment(3:end));
        case {9,10,11,12}
            % strings like YYMMDD+uni_name
            EXP_date = str2double(experiment(1:6));
        otherwise
            warning('Experiment date not ecognized, use default 999999')
            EXP_date = 999999;
    end
    
    %% Load bead coords, array or 3 columns.
    beadcoords = dlmread(beadcoords_pth);
    NoPosInput = length(pt);
    if NoPosInput ==1
        rownum = find(beadcoords(:,1)==pt);
        switch length(rownum)
            case 0
        error('Cannot find position=%d in beadcoords file.',...
               pt);
        case 1
        otherwise
        warning(['For pos %d, more than one record were found,',...
                 'use the first record'],pt)
        rownum  = rownum(1);
        end
    else
        rownum= zeros(NoPosInput,1);
        for j = 1:NoPosInput
            pt_element = pt(j);
            rownum_found = find(beadcoords(:,1)==pt_element);
            switch length(rownum_found)
                case 0
                    error('Cannot find position=%d in beadcoords file.',...
                           pt_element);
                case 1
                    rownum(j)  = rownum_found;
                otherwise
                    warning(['For pos %d, more than one record were found,',...
                             'use the first record'],pt_element)
                    rownum(j)  = rownum_found(1);
            end
        end
    end

    %% output 
    if     EXP_date >= 100000 &&  EXP_date <= 199999
        % orientation after 20170401 but before 20180901
        % orientation with which the pipettePointTo = 'down'
        xgb        = beadcoords(rownum,3);
        ygb        = beadcoords(rownum,2)*-1;
    elseif EXP_date >= 200000 &&  EXP_date <= 299999
        % orientation before 20170401
        % orientation with which the pipettePointTo = 'right'
        xgb        = beadcoords(rownum,2)*-1;
        ygb        = beadcoords(rownum,3)*-1;
    else % pipettePointTo = 'down'
        xgb        = beadcoords(rownum,3);
        ygb        = beadcoords(rownum,2)*-1;
    end

end