double_panel_fig_setting;
set(gcf,'Position',[0.1,0.1,0.4,0.8])
    ax1 = plot(avg_vy, avg_vx, 'o', 'MarkerSize',6, 'linewidth', 1, ...
                'color',[0,0,1,0.5]   ); hold on 
    ax2 = plot(avg_V + vy_shift ,avg_U + vx_shift ,...
               'o', 'MarkerSize',6, 'linewidth', 1, ...
               'color',[orange,0.5]  );  
    title([sprintf('exp:%s, bead pos.: %02d--(%.1f,%.1f)$\\mu$m\n',...
          experiment,pt,xgb,ygb),...
          'Compare EXP and CFD avg. limit cycle'],...
          'FontSize',12,'FontWeight','normal');    

    x_cent   = mean(avg_U);  
    y_cent   = mean(avg_V);
    quiver ( y_cent,   x_cent,  vy_shift, vx_shift,...
             'AutoScaleFactor',1.0,'LineWidth', 1, ...
             'MaxHeadSize'    ,0.5,'color',    'k'    );
    note_txt = ['$v_{shift}^{ax}$ = ',num2str(vx_shift,'%.2f'),'$\\mu$m/s\n',...
                '$v_{shift}^{lat}$ = ',num2str(vy_shift,'%.2f'),'$\\mu$m/s'];
    text   ( x_cent, y_cent-20,  sprintf(note_txt) , ...
             'Fontsize', 10, 'FontWeight', 'bold' );


    xlabel('Axial flow speed ($\mu$m/s)');      
    ylabel('Lateral flow speed ($\mu$m/s)');
    xlim([plt_v_span_min*0.5,plt_v_span_max*0.5]);    
    ylim([plt_v_span_min*0.5,plt_v_span_max*0.5]);
    axis('equal')   ;     grid('on');
    legend([ax1,ax2],{'EXP','CFD'},...
           'FontSize',12,'FontWeight','normal')
    set ( gcf, 'NextPlot','Replace');    

