function [yes_button,...
          no_button       ] = ui_use_previous_crops(h_fig,...
                              yes_butt_pos,no_butt_pos)
    yes_button = uicontrol('Style','Pushbutton',...
        'String','Yes, Use previous','Units','normalized',...
        'Position',yes_butt_pos,'Fontsize',12,...
        'FontWeight','bold','BackgroundColor','w',...
        'Callback',{@yes,h_fig}); %#ok<*NASGU>
    no_button  = uicontrol('Style','Pushbutton',...
        'String','No, I define','Units','normalized',...
        'Position',no_butt_pos,'Fontsize',12,...
        'FontWeight','bold','BackgroundColor','w',...
        'Callback',{@no,h_fig});
    
    function yes(~,~,h_fig)
        setappdata(h_fig,'use_previous_crops',1);
        uiresume(h_fig);
    end

    function no(~,~,h_fig)
        setappdata(h_fig,'use_previous_crops',0);
        uiresume(h_fig);
    end
end