function where_to_find_f_imp = ui_where_to_find_f_imp
    
    dialog_box = dialog('Units','normalized','Position',[0.35 0.42 0.3 0.16],'Name','Tell me');
    setappdata(dialog_box,'choice','');
    
    uicontrol('Parent',dialog_box,'Units','normalized',...
              'Position',[0.2 0.7 0.6 0.2],'Style','text',...
              'String','Where to find imposed freq.?',...
              'Fontsize',12,'Fontweight','bold');
       
    button1_string = 'Folder name';
    button2_string = 'Spectrum selection';
    button3_string = 'Manual input';
    button4_string = 'No imposed freq.';
    
    %button 1
    uicontrol('Parent',dialog_box,'Units','normalized',...
              'Position',[0.02 0.1 0.2 0.25],'Style','Pushbutton',...
              'String',button1_string,...
              'Callback',{@pass_string,button1_string});
    %button 2
    uicontrol('Parent',dialog_box,'Units','normalized',...
              'Position',[0.27 0.1 0.2 0.25],'Style','Pushbutton',...
              'String',button2_string,...
              'Callback',{@pass_string,button2_string});
    %button 3
    uicontrol('Parent',dialog_box,'Units','normalized',...
              'Position',[0.52 0.1 0.2 0.25],'Style','Pushbutton',...
              'String',button3_string,...
              'Callback',{@pass_string,button3_string});
    %button 4
    uicontrol('Parent',dialog_box,'Units','normalized',...
              'Position',[0.77 0.1 0.2 0.25],'Style','Pushbutton',...
              'String',button4_string,...
              'Callback',{@pass_string,button4_string});
                      
    function pass_string(~,~,string)
        setappdata(dialog_box,'choice',string);
        uiresume(dialog_box)
    end
                      
    uiwait(dialog_box);
    where_to_find_f_imp = getappdata(dialog_box,'choice');
    delete(dialog_box);
end
       