function h_text = ui_textbox(string,position)
    h_text =  uicontrol('Style','text','String',string,...
                        'Units','normalized','Position',position,...
                        'Fontsize',12,'FontWeight','normal');
end
