AB00_experimentalConditions
mama_folder_path_list={...
    'P:\000 Fast Cam Data\180710 wt beating in 5mM Ca\5mM Ca\',...
    'P:\000 Fast Cam Data\180710 wt beating in Normal tris\0.33mM Ca\',...
    };
slipRateTable = table();

saveToFdpth = 'D:\000 RAW DATA FILES\181128 slip rate under different calcium concentration';

for i_exp  = 1:2
    experiment_fdpth = mama_folder_path_list{i_exp}
    switch i_exp
        case 1
            expCondition = expConditionSet{6};
            calciumConcentration = getCalciumConcentration(expCondition);
        case 2
            expCondition = expConditionSet{3};
            calciumConcentration = getCalciumConcentration(expCondition);
    end
    expDate = '180710';
    for i_cell = 1:12
        experiment = [expDate,' c',num2str(i_cell,'%02d')];
    
        %% 1.check directory existence
        freeBeat = 1;
        freeBeatBefore = 1;
        img_before_fdpth = fullfile(experiment_fdpth,...
                           ['c',num2str(i_cell,'%02d')]);
        phaseInfo_before_pth = fullfile(experiment_fdpth,...
                               ['Folder_c',num2str(i_cell,'%02d'),'.mat']);
         
        %% 2.register number of slips
        Fs_interp = 1000; %all phases are resampled @1kHz in the routine

        % The begining and ending are each cut by 0.25 sec, as the phases are
        % often not stablized due to multiple smooth() and diff() in the
        % analysis routine

        load(phaseInfo_before_pth,'t_interflag_interp',...
             'Ph_interflag_interp','flag1_f','flag2_f')
        duration_before = t_interflag_interp(end) - 0.5;
        N_slip  = abs(Ph_interflag_interp(end-floor(0.25*Fs_interp))-...
                      Ph_interflag_interp(ceil(0.25*Fs_interp))); 
        NoSlip_before = floor(N_slip);
        avgFreq_before  = mean([mean(flag1_f),mean(flag2_f)]);
        stdFreq_before  = mean([std(flag1_f),std(flag2_f)]);

        %% 3.Check if there are misrecognition of the slips
        idx_realSlip_before        = [];
        idx_falseSlip_before       = [];
        REDO_before                = 'No';

        if NoSlip_before == 0
            NoSlip_manuReal_before = 0;
            NoSlip_manuFalse_before = 0;
        else
            load(phaseInfo_before_pth,'t_interflag_interp',...
                 'Ph_interflag_interp','Fs')
             fps = Fs;
            [NoSlip_manuReal_before,...
             NoSlip_manuFalse_before,...
             idx_realSlip_before,...
             idx_falseSlip_before] =  checkPhaseSlipByUser(Ph_interflag_interp,...
                                      img_before_fdpth,fps,Fs_interp);
            if NoSlip_manuFalse_before == 9999
                REDO_before   =  'YES';
            end
        end
    
    
        %% 4. register all the values
        resultThisExp_before = {experiment,expDate,'before',...
                                expCondition,calciumConcentration,...
                                freeBeatBefore,...
                                img_before_fdpth,...
                                phaseInfo_before_pth,...
                                duration_before,...
                                NoSlip_before,...
                                avgFreq_before,...
                                stdFreq_before,...
                                NoSlip_manuReal_before,...
                                NoSlip_manuFalse_before,...
                                idx_realSlip_before,...
                                idx_falseSlip_before,...
                                REDO_before};

        slipRateTable = [slipRateTable;resultThisExp_before]; %#ok<AGROW>
    end
    disp([num2str(i_exp),'/',num2str(numel(mama_folder_path_list)), 'done'])
end
varNames    = {'experiment','date','beforePiezoFlow',...
               'expCondition','calciumConcentration',...
               'freeBeatRecordExist',...
               'imageFolderPath',...
               'phaseMatFilePath',...
               'recordDuration',...
               'phaseChangeInRecord',...
               'avgFreq',...
               'stdFreq',...
               'NoSlipConfirmed',...
               'NoSlipMisRecog',...
               'posOfSlip',...
               'posOfMisreog',...
               'needRedefFIW'};
slipRateTable.Properties.VariableNames= varNames;
save(fullfile(saveToFdpth,'slipRateTable_2.mat'),'slipRateTable');